import 'dart:io';
import 'package:flutter/services.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import 'package:http/http.dart' as http;
import '../../core/utils/currency_formatter.dart';
import '../../core/utils/date_formatter.dart';
import '../business_profile/domain/business_profile_model.dart';
import '../documents/domain/document_model.dart';
import 'template_registry.dart';

class DocumentPdfGenerator {
  DocumentPdfGenerator._();


  static final Map<String, Uint8List> _imageCache = {};

  static Future<Uint8List?> _fetchImageBytes(String path) async {
    if (path.isEmpty) return null;
    if (_imageCache.containsKey(path)) return _imageCache[path];

    try {
      if (path.startsWith('http')) {
        final response = await http.get(Uri.parse(path));
        if (response.statusCode == 200) {
          _imageCache[path] = response.bodyBytes;
          return response.bodyBytes;
        }
      } else {
        final file = File(path);
        if (await file.exists()) {
          final bytes = await file.readAsBytes();
          _imageCache[path] = bytes;
          return bytes;
        }
      }
    } catch (_) {}
    return null;
  }



  static Future<Uint8List> generate({
    required DocumentModel document,
    required BusinessProfile profile,
    String? templateId,
  }) async {
    final pdf = pw.Document(
      title: '${document.docType.displayName} ${document.docNumber}',
      author: profile.businessName.isNotEmpty ? profile.businessName : 'invoz',
    );

    final selectedTemplate = templateId ?? document.templateId;
    final Uint8List? logoBytes = profile.logoPath != null
        ? await _fetchImageBytes(profile.logoPath!)
        : null;
    final Uint8List? signatureBytes = profile.signaturePath != null
        ? await _fetchImageBytes(profile.signaturePath!)
        : null;

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(32),
        footer: (context) => pw.Container(
          margin: const pw.EdgeInsets.only(top: 16),
          child: pw.Row(
            mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
            children: [
              pw.Text(
                'Generated by Invoz',
                style: const pw.TextStyle(fontSize: 8, color: PdfColors.grey),
              ),
              pw.Text(
                'Page ${context.pageNumber} of ${context.pagesCount}',
                style: const pw.TextStyle(fontSize: 8, color: PdfColors.grey),
              ),
            ],
          ),
        ),
        build: (context) {
          if (selectedTemplate == TemplateRegistry.premiumModern) {
            return _buildPremiumModern(
              context,
              document,
              profile,
              logoBytes: logoBytes,
              signatureBytes: signatureBytes,
            );
          }
          return _buildFreeClassic(
            context,
            document,
            profile,
            logoBytes: logoBytes,
            signatureBytes: signatureBytes,
          );
        },
      ),
    );

    return pdf.save();
  }

  static List<pw.Widget> _buildFreeClassic(
    pw.Context context,
    DocumentModel doc,
    BusinessProfile profile, {
    Uint8List? logoBytes,
    Uint8List? signatureBytes,
  }) {
    final title = doc.docType.displayName.toUpperCase();
    final cName = doc.customerSnapshot?.name ?? 'Unknown Customer';
    final cEmail = doc.customerSnapshot?.email ?? '';
    final cPhone = doc.customerSnapshot?.phone ?? '';
    final cAddress = doc.customerSnapshot?.billingAddress ?? '';

    return [
      pw.Row(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
        children: [
          pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              if (logoBytes != null)
                pw.Container(
                  height: 60,
                  width: 120,
                  alignment: pw.Alignment.centerLeft,
                  child: pw.Image(pw.MemoryImage(logoBytes)),
                ),
              pw.SizedBox(height: 8),
              pw.Text(
                profile.businessName,
                style: pw.TextStyle(
                  fontSize: 18,
                  fontWeight: pw.FontWeight.bold,
                ),
              ),
              if (profile.email != null && profile.email!.isNotEmpty)
                pw.Text(
                  profile.email!,
                  style: const pw.TextStyle(
                    fontSize: 10,
                    color: PdfColors.grey700,
                  ),
                ),
              if (profile.phone != null && profile.phone!.isNotEmpty)
                pw.Text(
                  profile.phone!,
                  style: const pw.TextStyle(
                    fontSize: 10,
                    color: PdfColors.grey700,
                  ),
                ),
              if (profile.address != null && profile.address!.isNotEmpty)
                pw.Text(
                  profile.address!,
                  style: const pw.TextStyle(
                    fontSize: 10,
                    color: PdfColors.grey700,
                  ),
                ),
              if (profile.gstin != null && profile.gstin!.isNotEmpty)
                pw.Text(
                  'GSTIN: ${profile.gstin!}',
                  style: const pw.TextStyle(
                    fontSize: 10,
                    color: PdfColors.grey700,
                  ),
                ),
            ],
          ),
          pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.end,
            children: [
              pw.Text(
                title,
                style: pw.TextStyle(
                  fontSize: 24,
                  fontWeight: pw.FontWeight.bold,
                  color: PdfColors.grey800,
                ),
              ),
              pw.SizedBox(height: 8),
              pw.Text(
                '# ${doc.docNumber}',
                style: pw.TextStyle(
                  fontSize: 12,
                  fontWeight: pw.FontWeight.bold,
                ),
              ),
              pw.Text(
                'Date: ${DateFormatter.format(doc.issueDate)}',
                style: const pw.TextStyle(fontSize: 10),
              ),
              pw.Text(
                'Due: ${DateFormatter.format(doc.dueDate)}',
                style: const pw.TextStyle(fontSize: 10),
              ),
            ],
          ),
        ],
      ),
      pw.SizedBox(height: 30),
      pw.Row(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Expanded(
            child: pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                pw.Text(
                  'BILL TO:',
                  style: pw.TextStyle(
                    fontSize: 10,
                    fontWeight: pw.FontWeight.bold,
                    color: PdfColors.grey600,
                  ),
                ),
                pw.SizedBox(height: 4),
                pw.Text(
                  cName,
                  style: pw.TextStyle(
                    fontSize: 12,
                    fontWeight: pw.FontWeight.bold,
                  ),
                ),
                if (cEmail.isNotEmpty)
                  pw.Text(cEmail, style: const pw.TextStyle(fontSize: 10)),
                if (cPhone.isNotEmpty)
                  pw.Text(cPhone, style: const pw.TextStyle(fontSize: 10)),
                if (cAddress.isNotEmpty)
                  pw.Text(cAddress, style: const pw.TextStyle(fontSize: 10)),
              ],
            ),
          ),
        ],
      ),
      pw.SizedBox(height: 30),
      _buildTable(doc, isPremium: false),
      pw.SizedBox(height: 20),
      pw.Row(
        mainAxisAlignment: pw.MainAxisAlignment.end,
        children: [
          pw.Container(
            width: 200,
            child: pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.end,
              children: [
                _buildSummaryRow(
                  'Subtotal',
                  CurrencyFormatter.format(doc.subtotal, symbol: 'Rs.'),
                ),
                if (doc.totalTaxAmount > 0)
                  _buildSummaryRow(
                    'Tax',
                    CurrencyFormatter.format(doc.totalTaxAmount, symbol: 'Rs.'),
                  ),
                if ((doc.overallDiscountAmount + doc.itemDiscountsTotal) > 0)
                  _buildSummaryRow(
                    'Discount',
                    '-${CurrencyFormatter.format(doc.overallDiscountAmount + doc.itemDiscountsTotal, symbol: 'Rs.')}',
                  ),
                pw.Divider(),
                _buildSummaryRow(
                  'Total',
                  CurrencyFormatter.format(doc.totalAmount, symbol: 'Rs.'),
                  isBold: true,
                  size: 14,
                ),
                if (doc.totalPaid > 0) ...[
                  pw.SizedBox(height: 4),
                  _buildSummaryRow(
                    'Amount Paid',
                    CurrencyFormatter.format(doc.totalPaid, symbol: 'Rs.'),
                  ),
                  _buildSummaryRow(
                    'Balance Due',
                    CurrencyFormatter.format(doc.balanceDue, symbol: 'Rs.'),
                    isBold: true,
                  ),
                ],
              ],
            ),
          ),
        ],
      ),
      pw.SizedBox(height: 40),
      if (doc.notes != null && doc.notes!.isNotEmpty)
        pw.Column(
          crossAxisAlignment: pw.CrossAxisAlignment.start,
          children: [
            pw.Text(
              'Notes / Terms:',
              style: pw.TextStyle(fontSize: 10, fontWeight: pw.FontWeight.bold),
            ),
            pw.SizedBox(height: 4),
            pw.Text(
              doc.notes!,
              style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey700),
            ),
          ],
        ),
      pw.SizedBox(height: 40),
      pw.Row(
        mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
        crossAxisAlignment: pw.CrossAxisAlignment.end,
        children: [
          pw.Expanded(
            child: _buildPaymentDetails(doc, profile),
          ),
          if (signatureBytes != null)
            pw.Column(
              children: [
                pw.Image(pw.MemoryImage(signatureBytes), height: 50),
                pw.Container(width: 150, child: pw.Divider()),
                pw.Text(
                  'Authorized Signature',
                  style: const pw.TextStyle(
                    fontSize: 10,
                    color: PdfColors.grey700,
                  ),
                ),
              ],
            ),
        ],
      ),
    ];
  }

  static List<pw.Widget> _buildPremiumModern(
    pw.Context context,
    DocumentModel doc,
    BusinessProfile profile, {
    Uint8List? logoBytes,
    Uint8List? signatureBytes,
  }) {
    final title = doc.docType.displayName.toUpperCase();
    final primaryColor = PdfColor.fromHex('#2563EB'); // Blue accent

    final cName = doc.customerSnapshot?.name ?? 'Unknown Customer';
    final cEmail = doc.customerSnapshot?.email ?? '';
    final cPhone = doc.customerSnapshot?.phone ?? '';
    final cAddress = doc.customerSnapshot?.billingAddress ?? '';

    return [
      pw.Container(
        padding: const pw.EdgeInsets.all(20),
        decoration: pw.BoxDecoration(
          color: primaryColor,
          borderRadius: const pw.BorderRadius.all(pw.Radius.circular(8)),
        ),
        child: pw.Row(
          mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
          children: [
            pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                pw.Text(
                  title,
                  style: pw.TextStyle(
                    fontSize: 28,
                    fontWeight: pw.FontWeight.bold,
                    color: PdfColors.white,
                  ),
                ),
                pw.SizedBox(height: 4),
                pw.Text(
                  '# ${doc.docNumber}',
                  style: const pw.TextStyle(
                    fontSize: 12,
                    color: PdfColors.white,
                  ),
                ),
              ],
            ),
            pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.end,
              children: [
                pw.Text(
                  'Issue Date: ${DateFormatter.format(doc.issueDate)}',
                  style: const pw.TextStyle(
                    fontSize: 10,
                    color: PdfColors.white,
                  ),
                ),
                pw.Text(
                  'Due Date: ${DateFormatter.format(doc.dueDate)}',
                  style: const pw.TextStyle(
                    fontSize: 10,
                    color: PdfColors.white,
                  ),
                ),
              ],
            ),
          ],
        ),
      ),
      pw.SizedBox(height: 30),
      pw.Row(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
        children: [
          pw.Expanded(
            child: pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                pw.Text(
                  'FROM:',
                  style: pw.TextStyle(
                    fontSize: 10,
                    fontWeight: pw.FontWeight.bold,
                    color: primaryColor,
                  ),
                ),
                pw.SizedBox(height: 8),
                if (logoBytes != null)
                  pw.Container(
                    height: 40,
                    alignment: pw.Alignment.centerLeft,
                    child: pw.Image(pw.MemoryImage(logoBytes)),
                    margin: const pw.EdgeInsets.only(bottom: 8),
                  ),
                pw.Text(
                  profile.businessName,
                  style: pw.TextStyle(
                    fontSize: 12,
                    fontWeight: pw.FontWeight.bold,
                  ),
                ),
                if (profile.email != null && profile.email!.isNotEmpty)
                  pw.Text(
                    profile.email!,
                    style: const pw.TextStyle(fontSize: 10),
                  ),
                if (profile.phone != null && profile.phone!.isNotEmpty)
                  pw.Text(
                    profile.phone!,
                    style: const pw.TextStyle(fontSize: 10),
                  ),
                if (profile.address != null && profile.address!.isNotEmpty)
                  pw.Text(
                    profile.address!,
                    style: const pw.TextStyle(fontSize: 10),
                  ),
              ],
            ),
          ),
          pw.Expanded(
            child: pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.end,
              children: [
                pw.Text(
                  'BILL TO:',
                  style: pw.TextStyle(
                    fontSize: 10,
                    fontWeight: pw.FontWeight.bold,
                    color: primaryColor,
                  ),
                ),
                pw.SizedBox(height: 8),
                pw.Text(
                  cName,
                  style: pw.TextStyle(
                    fontSize: 12,
                    fontWeight: pw.FontWeight.bold,
                  ),
                ),
                if (cEmail.isNotEmpty)
                  pw.Text(cEmail, style: const pw.TextStyle(fontSize: 10)),
                if (cPhone.isNotEmpty)
                  pw.Text(cPhone, style: const pw.TextStyle(fontSize: 10)),
                if (cAddress.isNotEmpty)
                  pw.Text(cAddress, style: const pw.TextStyle(fontSize: 10)),
              ],
            ),
          ),
        ],
      ),
      pw.SizedBox(height: 30),
      _buildTable(doc, isPremium: true, primaryColor: primaryColor),
      pw.SizedBox(height: 20),
      pw.Row(
        mainAxisAlignment: pw.MainAxisAlignment.end,
        children: [
          pw.Container(
            width: 250,
            padding: const pw.EdgeInsets.all(12),
            decoration: pw.BoxDecoration(
              color: PdfColors.grey100,
              borderRadius: const pw.BorderRadius.all(pw.Radius.circular(8)),
            ),
            child: pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.end,
              children: [
                _buildSummaryRow(
                  'Subtotal',
                  CurrencyFormatter.format(doc.subtotal, symbol: 'Rs.'),
                ),
                if (doc.totalTaxAmount > 0)
                  _buildSummaryRow(
                    'Tax',
                    CurrencyFormatter.format(doc.totalTaxAmount, symbol: 'Rs.'),
                  ),
                if ((doc.overallDiscountAmount + doc.itemDiscountsTotal) > 0)
                  _buildSummaryRow(
                    'Discount',
                    '-${CurrencyFormatter.format(doc.overallDiscountAmount + doc.itemDiscountsTotal, symbol: 'Rs.')}',
                  ),
                pw.Divider(color: PdfColors.grey400),
                _buildSummaryRow(
                  'Total',
                  CurrencyFormatter.format(doc.totalAmount, symbol: 'Rs.'),
                  isBold: true,
                  size: 16,
                  color: primaryColor,
                ),
                if (doc.totalPaid > 0) ...[
                  pw.SizedBox(height: 8),
                  _buildSummaryRow(
                    'Amount Paid',
                    CurrencyFormatter.format(doc.totalPaid, symbol: 'Rs.'),
                  ),
                  _buildSummaryRow(
                    'Balance Due',
                    CurrencyFormatter.format(doc.balanceDue, symbol: 'Rs.'),
                    isBold: true,
                    size: 12,
                  ),
                ],
              ],
            ),
          ),
        ],
      ),
      pw.SizedBox(height: 40),
      if (doc.notes != null && doc.notes!.isNotEmpty)
        pw.Container(
          padding: const pw.EdgeInsets.all(12),
          decoration: pw.BoxDecoration(
            border: pw.Border(
              left: pw.BorderSide(color: primaryColor, width: 3),
            ),
            color: PdfColors.grey50,
          ),
          child: pw.Text(doc.notes!, style: const pw.TextStyle(fontSize: 10)),
        ),
      pw.SizedBox(height: 40),
      pw.Row(
        mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
        crossAxisAlignment: pw.CrossAxisAlignment.end,
        children: [
          pw.Expanded(
            child: _buildPaymentDetails(doc, profile, primaryColor: primaryColor),
          ),
          if (signatureBytes != null)
            pw.Column(
              children: [
                pw.Image(pw.MemoryImage(signatureBytes), height: 50),
                pw.Container(
                  width: 150,
                  child: pw.Divider(color: primaryColor),
                ),
                pw.Text(
                  'Authorized Signature',
                  style: pw.TextStyle(
                    fontSize: 10,
                    color: primaryColor,
                    fontWeight: pw.FontWeight.bold,
                  ),
                ),
              ],
            ),
        ],
      ),
    ];
  }

  static pw.Widget _buildPaymentDetails(
    DocumentModel doc,
    BusinessProfile profile, {
    PdfColor? primaryColor,
  }) {
    final hasBank = profile.bankName != null &&
        profile.bankName!.trim().isNotEmpty &&
        profile.accountNumber != null &&
        profile.accountNumber!.trim().isNotEmpty;
    final hasUpi = profile.upiId != null && profile.upiId!.trim().isNotEmpty;

    if (!hasBank && !hasUpi) return pw.SizedBox();

    return pw.Container(
      child: pw.Row(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          if (hasUpi)
            pw.BarcodeWidget(
              barcode: pw.Barcode.qrCode(),
              data: 'upi://pay?pa=${profile.upiId}&pn=${Uri.encodeComponent(profile.businessName)}',
              width: 55,
              height: 55,
            ),
          if (hasUpi && hasBank) pw.SizedBox(width: 10),
          pw.Expanded(
            child: pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                pw.Text(
                  'Payment Details',
                  style: pw.TextStyle(
                    fontSize: 10,
                    fontWeight: pw.FontWeight.bold,
                    color: primaryColor ?? PdfColors.grey700,
                  ),
                ),
                pw.SizedBox(height: 4),
                if (hasBank) ...[
                  pw.Text('Bank: ${profile.bankName}', style: const pw.TextStyle(fontSize: 10)),
                  pw.Text('A/C No: ${profile.accountNumber}', style: const pw.TextStyle(fontSize: 10)),
                  if (profile.ifscCode != null && profile.ifscCode!.trim().isNotEmpty)
                    pw.Text('IFSC: ${profile.ifscCode}', style: const pw.TextStyle(fontSize: 10)),
                ],
                if (hasUpi)
                  pw.Text('UPI: ${profile.upiId}', style: const pw.TextStyle(fontSize: 10)),
              ],
            ),
          ),
        ],
      ),
    );
  }

  static pw.Widget _buildTable(
    DocumentModel doc, {
    required bool isPremium,
    PdfColor? primaryColor,
  }) {
    final headers = ['Item', 'Qty', 'Price', 'Tax', 'Total'];
    final data = doc.items.map((item) {
      return [
        item.title,
        item.quantity.toString(),
        CurrencyFormatter.format(item.unitPrice, symbol: 'Rs.'),
        item.taxPercent > 0 ? '${item.taxPercent}%' : '-',
        CurrencyFormatter.format(item.lineTotal, symbol: 'Rs.'),
      ];
    }).toList();

    if (isPremium) {
      return pw.TableHelper.fromTextArray(
        headers: headers,
        data: data,
        border: null,
        headerStyle: pw.TextStyle(
          color: PdfColors.white,
          fontWeight: pw.FontWeight.bold,
          fontSize: 10,
        ),
        headerDecoration: pw.BoxDecoration(
          color: primaryColor ?? PdfColors.blue,
        ),
        rowDecoration: const pw.BoxDecoration(
          border: pw.Border(
            bottom: pw.BorderSide(color: PdfColors.grey300, width: 0.5),
          ),
        ),
        cellStyle: const pw.TextStyle(fontSize: 10),
        cellAlignments: {
          0: pw.Alignment.centerLeft,
          1: pw.Alignment.center,
          2: pw.Alignment.centerRight,
          3: pw.Alignment.center,
          4: pw.Alignment.centerRight,
        },
      );
    } else {
      return pw.TableHelper.fromTextArray(
        headers: headers,
        data: data,
        border: const pw.TableBorder(
          bottom: pw.BorderSide(color: PdfColors.grey400),
          horizontalInside: pw.BorderSide(color: PdfColors.grey300),
        ),
        headerStyle: pw.TextStyle(fontWeight: pw.FontWeight.bold, fontSize: 10),
        cellStyle: const pw.TextStyle(fontSize: 10),
        cellAlignments: {
          0: pw.Alignment.centerLeft,
          1: pw.Alignment.center,
          2: pw.Alignment.centerRight,
          3: pw.Alignment.center,
          4: pw.Alignment.centerRight,
        },
      );
    }
  }

  static pw.Widget _buildSummaryRow(
    String label,
    String value, {
    bool isBold = false,
    double size = 10,
    PdfColor? color,
  }) {
    return pw.Padding(
      padding: const pw.EdgeInsets.symmetric(vertical: 2),
      child: pw.Row(
        mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
        children: [
          pw.Text(
            label,
            style: pw.TextStyle(
              fontSize: size,
              fontWeight: isBold ? pw.FontWeight.bold : pw.FontWeight.normal,
              color: color,
            ),
          ),
          pw.Text(
            value,
            style: pw.TextStyle(
              fontSize: size,
              fontWeight: isBold ? pw.FontWeight.bold : pw.FontWeight.normal,
              color: color,
            ),
          ),
        ],
      ),
    );
  }
}
