import 'dart:io';
import 'package:flutter/services.dart';
import 'package:invoz/features/settings/domain/payment_detail_model.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:http/http.dart' as http;
import '../../core/utils/image_cache_service.dart';
import '../../core/utils/currency_formatter.dart';
import '../../core/utils/date_formatter.dart';
import '../business_profile/domain/business_profile_model.dart';
import '../documents/domain/document_model.dart';
import 'template_registry.dart';

class DocumentPdfGenerator {
  DocumentPdfGenerator._();

  static final Map<String, Uint8List> _imageCache = {};

  static Future<Uint8List?> _fetchImageBytes(String path) async {
    if (path.isEmpty) return null;
    if (_imageCache.containsKey(path)) return _imageCache[path];

    try {
      // 1. Resolve local path via ImageCacheService if it's a remote URL
      // For caching key, we use a hash of the URL to ensure uniqueness
      String cacheKey = path.startsWith('http')
          ? 'pdf_img_${path.hashCode}'
          : '';
      String? resolvedPath = path.startsWith('http')
          ? await ImageCacheService.cacheImage(
              pathOrUrl: path,
              cacheKey: cacheKey,
            )
          : path;

      if (resolvedPath != null) {
        if (resolvedPath.startsWith('http')) {
          // Fallback to direct HTTP if caching failed but it's still a URL
          final response = await http
              .get(Uri.parse(resolvedPath))
              .timeout(const Duration(seconds: 5));
          if (response.statusCode == 200) {
            _imageCache[path] = response.bodyBytes;
            return response.bodyBytes;
          }
        } else {
          // Read local file
          final file = File(resolvedPath);
          if (await file.exists()) {
            final bytes = await file.readAsBytes();
            _imageCache[path] = bytes; // cache in-memory by original path
            return bytes;
          }
        }
      }
    } catch (_) {}
    return null;
  }

  static Future<Uint8List> generate({
    required DocumentModel document,
    required BusinessProfile profile,
    required List<PaymentDetail> payments,
    String? templateId,
  }) async {
    final pdf = pw.Document(
      title: '${document.docType.displayName} ${document.docNumber}',
      author: profile.businessName.isNotEmpty ? profile.businessName : 'invoz',
    );

    final selectedTemplate = templateId ?? document.templateId;
    final Uint8List? logoBytes = profile.logoPath != null
        ? await _fetchImageBytes(profile.logoPath!)
        : null;
    final Uint8List? signatureBytes = profile.signaturePath != null
        ? await _fetchImageBytes(profile.signaturePath!)
        : null;

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(32),
        footer: (context) => pw.Container(
          margin: const pw.EdgeInsets.only(top: 16),
          child: pw.Row(
            mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
            children: [
              pw.Text(
                'Generated by Invoz App',
                style: const pw.TextStyle(fontSize: 8, color: PdfColors.grey),
              ),
              pw.Text(
                'Page ${context.pageNumber} of ${context.pagesCount}',
                style: const pw.TextStyle(fontSize: 8, color: PdfColors.grey),
              ),
            ],
          ),
        ),
        build: (context) {
          if (selectedTemplate == TemplateRegistry.premiumModern) {
            return _buildPremiumModern(
              context,
              document,
              profile,
              payments: payments,
              logoBytes: logoBytes,
              signatureBytes: signatureBytes,
            );
          }
          if (selectedTemplate == TemplateRegistry.elegantCenter) {
            return _buildElegantCenter(
              context,
              document,
              profile,
              payments: payments,
              logoBytes: logoBytes,
              signatureBytes: signatureBytes,
            );
          }
          return _buildFreeClassic(
            context,
            document,
            profile,
            payments: payments,
            logoBytes: logoBytes,
            signatureBytes: signatureBytes,
          );
        },
      ),
    );

    return pdf.save();
  }

  static List<pw.Widget> _buildFreeClassic(
    pw.Context context,
    DocumentModel doc,
    BusinessProfile profile, {
    required List<PaymentDetail> payments,
    Uint8List? logoBytes,
    Uint8List? signatureBytes,
  }) {
    final title = doc.docType.displayName.toUpperCase();
    final primaryColor = PdfColor.fromHex('#0F172A'); // Slate 900
    final secondaryColor = PdfColor.fromHex('#475569'); // Slate 600
    final mutedColor = PdfColor.fromHex('#64748B'); // Slate 500
    final borderColor = PdfColor.fromHex('#E2E8F0'); // Slate 200
    final bgLight = PdfColor.fromHex('#F8FAFC'); // Slate 50
    final badgeBg = PdfColor.fromHex('#F1F5F9'); // Slate 100

    final cName = doc.customerSnapshot?.name ?? 'Unknown Customer';
    final cEmail = doc.customerSnapshot?.email ?? '';
    final cPhone = doc.customerSnapshot?.phone ?? '';
    final cAddress = doc.customerSnapshot?.billingAddress ?? '';

    return [
      // Top Header
      pw.Row(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
        children: [
          pw.Expanded(
            flex: 3,
            child: pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                if (logoBytes != null)
                  pw.Container(
                    height: 44,
                    width: 100,
                    alignment: pw.Alignment.centerLeft,
                    child: pw.Image(
                      pw.MemoryImage(logoBytes),
                      fit: pw.BoxFit.contain,
                    ),
                  ),
                pw.SizedBox(height: 8),
                pw.Text(
                  profile.businessName,
                  style: pw.TextStyle(
                    fontSize: 18,
                    fontWeight: pw.FontWeight.bold,
                    color: primaryColor,
                  ),
                ),
                pw.SizedBox(height: 4),
                if (profile.email != null && profile.email!.isNotEmpty)
                  pw.Text(
                    profile.email!,
                    style: pw.TextStyle(fontSize: 9.5, color: secondaryColor),
                  ),
                if (profile.phone != null && profile.phone!.isNotEmpty)
                  pw.Text(
                    profile.phone!,
                    style: pw.TextStyle(fontSize: 9.5, color: secondaryColor),
                  ),
                if (profile.address != null && profile.address!.isNotEmpty)
                  pw.Text(
                    profile.address!,
                    style: pw.TextStyle(fontSize: 9.5, color: secondaryColor),
                  ),
                if (profile.gstin != null && profile.gstin!.isNotEmpty)
                  pw.Text(
                    'GSTIN: ${profile.gstin!}',
                    style: pw.TextStyle(fontSize: 9.5, color: secondaryColor),
                  ),
              ],
            ),
          ),
          pw.Expanded(
            flex: 2,
            child: pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.end,
              children: [
                pw.Text(
                  title,
                  style: pw.TextStyle(
                    fontSize: 24,
                    fontWeight: pw.FontWeight.bold,
                    color: primaryColor,
                    letterSpacing: 1.5,
                  ),
                ),
                pw.SizedBox(height: 8),
                pw.Container(
                  padding: const pw.EdgeInsets.symmetric(
                    horizontal: 10,
                    vertical: 4,
                  ),
                  decoration: pw.BoxDecoration(
                    color: badgeBg,
                    borderRadius: const pw.BorderRadius.all(
                      pw.Radius.circular(6),
                    ),
                    border: pw.Border.all(color: borderColor),
                  ),
                  child: pw.Text(
                    '# ${doc.docNumber}',
                    style: pw.TextStyle(
                      fontSize: 11,
                      fontWeight: pw.FontWeight.bold,
                      color: primaryColor,
                    ),
                  ),
                ),
                pw.SizedBox(height: 8),
                pw.Row(
                  mainAxisSize: pw.MainAxisSize.min,
                  children: [
                    pw.Text(
                      'Issue Date: ',
                      style: pw.TextStyle(fontSize: 10, color: mutedColor),
                    ),
                    pw.Text(
                      DateFormatter.format(doc.issueDate),
                      style: pw.TextStyle(
                        fontSize: 10,
                        fontWeight: pw.FontWeight.bold,
                        color: primaryColor,
                      ),
                    ),
                  ],
                ),
                pw.SizedBox(height: 3),
                pw.Row(
                  mainAxisSize: pw.MainAxisSize.min,
                  children: [
                    pw.Text(
                      'Due Date: ',
                      style: pw.TextStyle(fontSize: 10, color: mutedColor),
                    ),
                    pw.Text(
                      DateFormatter.format(doc.dueDate),
                      style: pw.TextStyle(
                        fontSize: 10,
                        fontWeight: pw.FontWeight.bold,
                        color: primaryColor,
                      ),
                    ),
                  ],
                ),
              ],
            ),
          ),
        ],
      ),

      pw.SizedBox(height: 18),
      pw.Container(height: 1, color: borderColor),
      pw.SizedBox(height: 18),

      // Bill To & Total Due Card
      pw.Row(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
        children: [
          pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Text(
                'BILLED TO',
                style: pw.TextStyle(
                  fontSize: 9,
                  fontWeight: pw.FontWeight.bold,
                  color: mutedColor,
                  letterSpacing: 1.0,
                ),
              ),
              pw.SizedBox(height: 4),
              pw.Text(
                cName,
                style: pw.TextStyle(
                  fontSize: 13,
                  fontWeight: pw.FontWeight.bold,
                  color: primaryColor,
                ),
              ),
              pw.SizedBox(height: 2),
              if (cEmail.isNotEmpty)
                pw.Text(
                  cEmail,
                  style: pw.TextStyle(fontSize: 9.5, color: secondaryColor),
                ),
              if (cPhone.isNotEmpty)
                pw.Text(
                  cPhone,
                  style: pw.TextStyle(fontSize: 9.5, color: secondaryColor),
                ),
              if (cAddress.isNotEmpty)
                pw.Text(
                  cAddress,
                  style: pw.TextStyle(fontSize: 9.5, color: secondaryColor),
                ),
            ],
          ),
          pw.Container(
            padding: const pw.EdgeInsets.symmetric(horizontal: 14, vertical: 8),
            decoration: pw.BoxDecoration(
              color: bgLight,
              borderRadius: const pw.BorderRadius.all(pw.Radius.circular(8)),
              border: pw.Border.all(color: borderColor),
            ),
            child: pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.end,
              children: [
                pw.Text(
                  'TOTAL DUE',
                  style: pw.TextStyle(
                    fontSize: 8.5,
                    fontWeight: pw.FontWeight.bold,
                    color: mutedColor,
                  ),
                ),
                pw.SizedBox(height: 2),
                pw.Text(
                  CurrencyFormatter.format(doc.totalAmount, symbol: 'Rs.'),
                  style: pw.TextStyle(
                    fontSize: 15,
                    fontWeight: pw.FontWeight.bold,
                    color: primaryColor,
                  ),
                ),
              ],
            ),
          ),
        ],
      ),

      pw.SizedBox(height: 22),

      // Table Header
      pw.Container(
        padding: const pw.EdgeInsets.symmetric(vertical: 8, horizontal: 10),
        decoration: pw.BoxDecoration(
          color: badgeBg,
          borderRadius: const pw.BorderRadius.all(pw.Radius.circular(6)),
          border: pw.Border.all(color: borderColor),
        ),
        child: pw.Row(
          children: [
            pw.Expanded(
              flex: 4,
              child: pw.Text(
                'DESCRIPTION',
                style: pw.TextStyle(
                  fontSize: 9,
                  fontWeight: pw.FontWeight.bold,
                  color: secondaryColor,
                ),
              ),
            ),
            pw.Expanded(
              flex: 1,
              child: pw.Align(
                alignment: pw.Alignment.center,
                child: pw.Text(
                  'QTY',
                  style: pw.TextStyle(
                    fontSize: 9,
                    fontWeight: pw.FontWeight.bold,
                    color: secondaryColor,
                  ),
                ),
              ),
            ),
            pw.Expanded(
              flex: 2,
              child: pw.Align(
                alignment: pw.Alignment.centerRight,
                child: pw.Text(
                  'UNIT PRICE',
                  style: pw.TextStyle(
                    fontSize: 9,
                    fontWeight: pw.FontWeight.bold,
                    color: secondaryColor,
                  ),
                ),
              ),
            ),
            pw.Expanded(
              flex: 1,
              child: pw.Align(
                alignment: pw.Alignment.centerRight,
                child: pw.Text(
                  'TAX',
                  style: pw.TextStyle(
                    fontSize: 9,
                    fontWeight: pw.FontWeight.bold,
                    color: secondaryColor,
                  ),
                ),
              ),
            ),
            pw.Expanded(
              flex: 2,
              child: pw.Align(
                alignment: pw.Alignment.centerRight,
                child: pw.Text(
                  'AMOUNT',
                  style: pw.TextStyle(
                    fontSize: 9,
                    fontWeight: pw.FontWeight.bold,
                    color: secondaryColor,
                  ),
                ),
              ),
            ),
          ],
        ),
      ),

      // Table Items
      ...doc.items.map((item) {
        return pw.Container(
          padding: const pw.EdgeInsets.symmetric(vertical: 10, horizontal: 10),
          decoration: pw.BoxDecoration(
            border: pw.Border(bottom: pw.BorderSide(color: badgeBg)),
          ),
          child: pw.Row(
            children: [
              pw.Expanded(
                flex: 4,
                child: pw.Column(
                  crossAxisAlignment: pw.CrossAxisAlignment.start,
                  children: [
                    pw.Text(
                      item.title,
                      style: pw.TextStyle(
                        fontSize: 10.5,
                        fontWeight: pw.FontWeight.bold,
                        color: primaryColor,
                      ),
                    ),
                    if (item.description != null &&
                        item.description!.isNotEmpty)
                      pw.Padding(
                        padding: const pw.EdgeInsets.only(top: 2),
                        child: pw.Text(
                          item.description!,
                          style: pw.TextStyle(fontSize: 9, color: mutedColor),
                        ),
                      ),
                  ],
                ),
              ),
              pw.Expanded(
                flex: 1,
                child: pw.Align(
                  alignment: pw.Alignment.center,
                  child: pw.Text(
                    item.quantity.toString(),
                    style: pw.TextStyle(fontSize: 10, color: primaryColor),
                  ),
                ),
              ),
              pw.Expanded(
                flex: 2,
                child: pw.Align(
                  alignment: pw.Alignment.centerRight,
                  child: pw.Text(
                    CurrencyFormatter.format(item.unitPrice, symbol: 'Rs.'),
                    style: pw.TextStyle(fontSize: 10, color: primaryColor),
                  ),
                ),
              ),
              pw.Expanded(
                flex: 1,
                child: pw.Align(
                  alignment: pw.Alignment.centerRight,
                  child: pw.Text(
                    item.taxPercent > 0 ? '${item.taxPercent}%' : '-',
                    style: pw.TextStyle(fontSize: 10, color: secondaryColor),
                  ),
                ),
              ),
              pw.Expanded(
                flex: 2,
                child: pw.Align(
                  alignment: pw.Alignment.centerRight,
                  child: pw.Text(
                    CurrencyFormatter.format(item.lineTotal, symbol: 'Rs.'),
                    style: pw.TextStyle(
                      fontSize: 10.5,
                      fontWeight: pw.FontWeight.bold,
                      color: primaryColor,
                    ),
                  ),
                ),
              ),
            ],
          ),
        );
      }),

      pw.SizedBox(height: 18),

      // Summary Card
      pw.Align(
        alignment: pw.Alignment.centerRight,
        child: pw.Container(
          width: 220,
          padding: const pw.EdgeInsets.all(12),
          decoration: pw.BoxDecoration(
            color: bgLight,
            borderRadius: const pw.BorderRadius.all(pw.Radius.circular(8)),
            border: pw.Border.all(color: borderColor),
          ),
          child: pw.Column(
            children: [
              _buildSummaryRow(
                'Subtotal',
                CurrencyFormatter.format(doc.subtotal, symbol: 'Rs.'),
                size: 10,
                color: secondaryColor,
              ),
              if (doc.totalTaxAmount > 0)
                _buildSummaryRow(
                  'Tax',
                  CurrencyFormatter.format(doc.totalTaxAmount, symbol: 'Rs.'),
                  size: 10,
                  color: secondaryColor,
                ),
              if ((doc.overallDiscountAmount + doc.itemDiscountsTotal) > 0)
                _buildSummaryRow(
                  'Discount',
                  '-${CurrencyFormatter.format(doc.overallDiscountAmount + doc.itemDiscountsTotal, symbol: 'Rs.')}',
                  size: 10,
                  color: secondaryColor,
                ),
              pw.SizedBox(height: 6),
              pw.Container(height: 1, color: borderColor),
              pw.SizedBox(height: 6),
              _buildSummaryRow(
                'Total',
                CurrencyFormatter.format(doc.totalAmount, symbol: 'Rs.'),
                isBold: true,
                size: 13,
                color: primaryColor,
              ),
              if (doc.totalPaid > 0) ...[
                pw.SizedBox(height: 4),
                _buildSummaryRow(
                  'Amount Paid',
                  CurrencyFormatter.format(doc.totalPaid, symbol: 'Rs.'),
                  size: 10,
                  color: secondaryColor,
                ),
                _buildSummaryRow(
                  'Balance Due',
                  CurrencyFormatter.format(doc.balanceDue, symbol: 'Rs.'),
                  isBold: true,
                  size: 11,
                  color: primaryColor,
                ),
              ],
            ],
          ),
        ),
      ),

      pw.SizedBox(height: 16),

      // Notes & Terms Callout
      if (doc.notes != null && doc.notes!.isNotEmpty)
        pw.Container(
          padding: const pw.EdgeInsets.symmetric(horizontal: 12, vertical: 10),
          decoration: pw.BoxDecoration(
            color: bgLight,
            border: pw.Border(left: pw.BorderSide(color: mutedColor, width: 3)),
          ),
          child: pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Text(
                'Notes & Terms:',
                style: pw.TextStyle(
                  fontSize: 9.5,
                  fontWeight: pw.FontWeight.bold,
                  color: primaryColor,
                ),
              ),
              pw.SizedBox(height: 2),
              pw.Text(
                doc.notes!,
                style: pw.TextStyle(fontSize: 9.5, color: secondaryColor),
              ),
            ],
          ),
        ),

      pw.Spacer(),

      // Payment Details & Signature
      pw.Row(
        mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
        crossAxisAlignment: pw.CrossAxisAlignment.end,
        children: [
          pw.Expanded(
            child: _buildPaymentDetails(
              doc,
              payments,
              profile,
              primaryColor: primaryColor,
            ),
          ),
          if (signatureBytes != null)
            pw.Column(
              children: [
                pw.Image(pw.MemoryImage(signatureBytes), height: 40),
                pw.SizedBox(height: 4),
                pw.Container(width: 120, height: 1.5, color: borderColor),
                pw.SizedBox(height: 4),
                pw.Text(
                  'Authorized Signature',
                  style: pw.TextStyle(
                    fontSize: 9,
                    fontWeight: pw.FontWeight.bold,
                    color: mutedColor,
                  ),
                ),
              ],
            ),
        ],
      ),
    ];
  }

  static List<pw.Widget> _buildPremiumModern(
    pw.Context context,
    DocumentModel doc,
    BusinessProfile profile, {
    required List<PaymentDetail> payments,
    Uint8List? logoBytes,
    Uint8List? signatureBytes,
  }) {
    final title = doc.docType.displayName.toUpperCase();
    final primaryColor = PdfColor.fromHex('#2563EB'); // Blue accent

    final cName = doc.customerSnapshot?.name ?? 'Unknown Customer';
    final cEmail = doc.customerSnapshot?.email ?? '';
    final cPhone = doc.customerSnapshot?.phone ?? '';
    final cAddress = doc.customerSnapshot?.billingAddress ?? '';

    return [
      pw.Container(
        padding: const pw.EdgeInsets.all(20),
        decoration: pw.BoxDecoration(
          color: primaryColor,
          borderRadius: const pw.BorderRadius.all(pw.Radius.circular(8)),
        ),
        child: pw.Row(
          mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
          children: [
            pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                pw.Text(
                  title,
                  style: pw.TextStyle(
                    fontSize: 28,
                    fontWeight: pw.FontWeight.bold,
                    color: PdfColors.white,
                  ),
                ),
                pw.SizedBox(height: 4),
                pw.Text(
                  '# ${doc.docNumber}',
                  style: const pw.TextStyle(
                    fontSize: 12,
                    color: PdfColors.white,
                  ),
                ),
              ],
            ),
            pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.end,
              children: [
                pw.Text(
                  'Issue Date: ${DateFormatter.format(doc.issueDate)}',
                  style: const pw.TextStyle(
                    fontSize: 10,
                    color: PdfColors.white,
                  ),
                ),
                pw.Text(
                  'Due Date: ${DateFormatter.format(doc.dueDate)}',
                  style: const pw.TextStyle(
                    fontSize: 10,
                    color: PdfColors.white,
                  ),
                ),
              ],
            ),
          ],
        ),
      ),
      pw.SizedBox(height: 30),
      pw.Row(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
        children: [
          pw.Expanded(
            child: pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                pw.Text(
                  'FROM:',
                  style: pw.TextStyle(
                    fontSize: 10,
                    fontWeight: pw.FontWeight.bold,
                    color: primaryColor,
                  ),
                ),
                pw.SizedBox(height: 8),
                if (logoBytes != null)
                  pw.Container(
                    height: 40,
                    alignment: pw.Alignment.centerLeft,
                    child: pw.Image(pw.MemoryImage(logoBytes)),
                    margin: const pw.EdgeInsets.only(bottom: 8),
                  ),
                pw.Text(
                  profile.businessName,
                  style: pw.TextStyle(
                    fontSize: 12,
                    fontWeight: pw.FontWeight.bold,
                  ),
                ),
                if (profile.email != null && profile.email!.isNotEmpty)
                  pw.Text(
                    profile.email!,
                    style: const pw.TextStyle(fontSize: 10),
                  ),
                if (profile.phone != null && profile.phone!.isNotEmpty)
                  pw.Text(
                    profile.phone!,
                    style: const pw.TextStyle(fontSize: 10),
                  ),
                if (profile.address != null && profile.address!.isNotEmpty)
                  pw.Text(
                    profile.address!,
                    style: const pw.TextStyle(fontSize: 10),
                  ),
              ],
            ),
          ),
          pw.Expanded(
            child: pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.end,
              children: [
                pw.Text(
                  'BILL TO:',
                  style: pw.TextStyle(
                    fontSize: 10,
                    fontWeight: pw.FontWeight.bold,
                    color: primaryColor,
                  ),
                ),
                pw.SizedBox(height: 8),
                pw.Text(
                  cName,
                  style: pw.TextStyle(
                    fontSize: 12,
                    fontWeight: pw.FontWeight.bold,
                  ),
                ),
                if (cEmail.isNotEmpty)
                  pw.Text(cEmail, style: const pw.TextStyle(fontSize: 10)),
                if (cPhone.isNotEmpty)
                  pw.Text(cPhone, style: const pw.TextStyle(fontSize: 10)),
                if (cAddress.isNotEmpty)
                  pw.Text(cAddress, style: const pw.TextStyle(fontSize: 10)),
              ],
            ),
          ),
        ],
      ),
      pw.SizedBox(height: 30),
      _buildTable(doc, isPremium: true, primaryColor: primaryColor),
      pw.SizedBox(height: 20),
      pw.Row(
        mainAxisAlignment: pw.MainAxisAlignment.end,
        children: [
          pw.Container(
            width: 250,
            padding: const pw.EdgeInsets.all(12),
            decoration: pw.BoxDecoration(
              color: PdfColors.grey100,
              borderRadius: const pw.BorderRadius.all(pw.Radius.circular(8)),
            ),
            child: pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.end,
              children: [
                _buildSummaryRow(
                  'Subtotal',
                  CurrencyFormatter.format(doc.subtotal, symbol: 'Rs.'),
                ),
                if (doc.totalTaxAmount > 0)
                  _buildSummaryRow(
                    'Tax',
                    CurrencyFormatter.format(doc.totalTaxAmount, symbol: 'Rs.'),
                  ),
                if ((doc.overallDiscountAmount + doc.itemDiscountsTotal) > 0)
                  _buildSummaryRow(
                    'Discount',
                    '-${CurrencyFormatter.format(doc.overallDiscountAmount + doc.itemDiscountsTotal, symbol: 'Rs.')}',
                  ),
                pw.Divider(color: PdfColors.grey400),
                _buildSummaryRow(
                  'Total',
                  CurrencyFormatter.format(doc.totalAmount, symbol: 'Rs.'),
                  isBold: true,
                  size: 16,
                  color: primaryColor,
                ),
                if (doc.totalPaid > 0) ...[
                  pw.SizedBox(height: 8),
                  _buildSummaryRow(
                    'Amount Paid',
                    CurrencyFormatter.format(doc.totalPaid, symbol: 'Rs.'),
                  ),
                  _buildSummaryRow(
                    'Balance Due',
                    CurrencyFormatter.format(doc.balanceDue, symbol: 'Rs.'),
                    isBold: true,
                    size: 12,
                  ),
                ],
              ],
            ),
          ),
        ],
      ),
      pw.SizedBox(height: 40),
      if (doc.notes != null && doc.notes!.isNotEmpty)
        pw.Container(
          padding: const pw.EdgeInsets.all(12),
          decoration: pw.BoxDecoration(
            border: pw.Border(
              left: pw.BorderSide(color: primaryColor, width: 3),
            ),
            color: PdfColors.grey50,
          ),
          child: pw.Text(doc.notes!, style: const pw.TextStyle(fontSize: 10)),
        ),
      pw.SizedBox(height: 40),
      pw.Row(
        mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
        crossAxisAlignment: pw.CrossAxisAlignment.end,
        children: [
          pw.Expanded(
            child: _buildPaymentDetails(
              doc,
              payments,
              profile,
              primaryColor: primaryColor,
            ),
          ),
          if (signatureBytes != null)
            pw.Column(
              children: [
                pw.Image(pw.MemoryImage(signatureBytes), height: 50),
                pw.Container(
                  width: 150,
                  child: pw.Divider(color: primaryColor),
                ),
                pw.Text(
                  'Authorized Signature',
                  style: pw.TextStyle(
                    fontSize: 10,
                    color: primaryColor,
                    fontWeight: pw.FontWeight.bold,
                  ),
                ),
              ],
            ),
        ],
      ),
    ];
  }

  static pw.Widget _buildPaymentDetails(
    DocumentModel doc,
    List<PaymentDetail> payments,
    BusinessProfile profile, {
    PdfColor? primaryColor,
  }) {
    PaymentDetail? bankDetail;
    if (doc.selectedBankDetailId != null &&
        doc.selectedBankDetailId != 'none') {
      try {
        bankDetail = payments.firstWhere(
          (p) => p.id == doc.selectedBankDetailId,
        );
      } catch (_) {}
    }
    if (bankDetail == null &&
        doc.selectedBankDetailId != 'none' &&
        profile.bankName != null &&
        profile.bankName!.trim().isNotEmpty &&
        profile.accountNumber != null &&
        profile.accountNumber!.trim().isNotEmpty) {
      bankDetail = PaymentDetail(
        id: 'legacy',
        type: 'Bank',
        title: profile.bankName!,
        details: profile.accountNumber!,
        extra: profile.ifscCode,
      );
    }
    if (bankDetail == null && doc.selectedBankDetailId != 'none') {
      final banks = payments.where((p) => p.type == 'Bank').toList();
      if (banks.isNotEmpty) bankDetail = banks.first;
    }

    PaymentDetail? upiDetail;
    if (doc.selectedUpiDetailId != null && doc.selectedUpiDetailId != 'none') {
      try {
        upiDetail = payments.firstWhere((p) => p.id == doc.selectedUpiDetailId);
      } catch (_) {}
    }
    if (upiDetail == null &&
        doc.selectedUpiDetailId != 'none' &&
        profile.upiId != null &&
        profile.upiId!.trim().isNotEmpty) {
      upiDetail = PaymentDetail(
        id: 'legacy_upi',
        type: 'UPI',
        title: 'UPI',
        details: profile.upiId!,
      );
    }
    if (upiDetail == null && doc.selectedUpiDetailId != 'none') {
      final upis = payments.where((p) => p.type == 'UPI').toList();
      if (upis.isNotEmpty) upiDetail = upis.first;
    }

    final hasBank = bankDetail != null;
    final hasUpi = upiDetail != null;

    if (!doc.includePaymentDetails || doc.docType == DocumentType.receipt) {
      return pw.SizedBox();
    }
    if (!hasBank && !hasUpi) return pw.SizedBox();

    return pw.Container(
      child: pw.Row(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Column(
            children: [
              pw.Container(
                width: 60,
                height: 60,
                padding: const pw.EdgeInsets.all(4),
                decoration: pw.BoxDecoration(
                  color: PdfColors.white,
                  borderRadius: const pw.BorderRadius.all(
                    pw.Radius.circular(6),
                  ),
                  border: pw.Border.all(color: PdfColors.grey400, width: 1),
                ),
                child: hasUpi
                    ? pw.BarcodeWidget(
                        barcode: pw.Barcode.qrCode(),
                        data:
                            'upi://pay?pa=${upiDetail.details}&pn=${Uri.encodeComponent(profile.businessName)}&am=${doc.totalAmount}',
                      )
                    : pw.BarcodeWidget(
                        barcode: pw.Barcode.qrCode(),
                        data: 'https://invoz.com',
                      ),
              ),
              pw.SizedBox(height: 4),
              pw.Text(
                'Scan to Pay',
                style: pw.TextStyle(
                  fontSize: 8,
                  fontWeight: pw.FontWeight.bold,
                  color: PdfColors.grey700,
                ),
              ),
            ],
          ),
          pw.SizedBox(width: 16),
          pw.Expanded(
            child: pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                pw.Text(
                  'PAYMENT DETAILS',
                  style: pw.TextStyle(
                    fontSize: 10,
                    fontWeight: pw.FontWeight.bold,
                    letterSpacing: 0.6,
                    color: primaryColor ?? PdfColors.grey800,
                  ),
                ),
                pw.SizedBox(height: 6),
                if (hasUpi)
                  pw.Padding(
                    padding: const pw.EdgeInsets.only(bottom: 4),
                    child: pw.Text(
                      'UPI (${upiDetail.title}): ${upiDetail.details}',
                      style: pw.TextStyle(
                        fontSize: 10,
                        fontWeight: pw.FontWeight.bold,
                      ),
                    ),
                  ),
                if (hasBank) ...[
                  pw.Text(
                    'Bank: ${bankDetail.title}',
                    style: pw.TextStyle(
                      fontSize: 10,
                      fontWeight: pw.FontWeight.bold,
                    ),
                  ),
                  pw.SizedBox(height: 1),
                  pw.Text(
                    'A/C: ${bankDetail.details}',
                    style: const pw.TextStyle(fontSize: 10),
                  ),
                  if (bankDetail.extra != null &&
                      bankDetail.extra!.trim().isNotEmpty)
                    pw.Text(
                      'IFSC: ${bankDetail.extra}',
                      style: const pw.TextStyle(
                        fontSize: 9,
                        color: PdfColors.grey700,
                      ),
                    ),
                ],
              ],
            ),
          ),
        ],
      ),
    );
  }

  static pw.Widget _buildTable(
    DocumentModel doc, {
    required bool isPremium,
    PdfColor? primaryColor,
  }) {
    final headers = ['Item', 'Qty', 'Price', 'Tax', 'Total'];
    final data = doc.items.map((item) {
      return [
        item.title,
        item.quantity.toString(),
        CurrencyFormatter.format(item.unitPrice, symbol: 'Rs.'),
        item.taxPercent > 0 ? '${item.taxPercent}%' : '-',
        CurrencyFormatter.format(item.lineTotal, symbol: 'Rs.'),
      ];
    }).toList();

    if (isPremium) {
      return pw.TableHelper.fromTextArray(
        headers: headers,
        data: data,
        border: null,
        headerStyle: pw.TextStyle(
          color: PdfColors.white,
          fontWeight: pw.FontWeight.bold,
          fontSize: 10,
        ),
        headerDecoration: pw.BoxDecoration(
          color: primaryColor ?? PdfColors.blue,
        ),
        rowDecoration: const pw.BoxDecoration(
          border: pw.Border(
            bottom: pw.BorderSide(color: PdfColors.grey300, width: 0.5),
          ),
        ),
        cellStyle: const pw.TextStyle(fontSize: 10),
        cellAlignments: {
          0: pw.Alignment.centerLeft,
          1: pw.Alignment.center,
          2: pw.Alignment.centerRight,
          3: pw.Alignment.center,
          4: pw.Alignment.centerRight,
        },
      );
    } else {
      return pw.TableHelper.fromTextArray(
        headers: headers,
        data: data,
        border: const pw.TableBorder(
          bottom: pw.BorderSide(color: PdfColors.grey400),
          horizontalInside: pw.BorderSide(color: PdfColors.grey300),
        ),
        headerStyle: pw.TextStyle(fontWeight: pw.FontWeight.bold, fontSize: 10),
        cellStyle: const pw.TextStyle(fontSize: 10),
        cellAlignments: {
          0: pw.Alignment.centerLeft,
          1: pw.Alignment.center,
          2: pw.Alignment.centerRight,
          3: pw.Alignment.center,
          4: pw.Alignment.centerRight,
        },
      );
    }
  }

  static pw.Widget _buildSummaryRow(
    String label,
    String value, {
    bool isBold = false,
    double size = 10,
    PdfColor? color,
  }) {
    return pw.Padding(
      padding: const pw.EdgeInsets.symmetric(vertical: 2),
      child: pw.Row(
        mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
        children: [
          pw.Text(
            label,
            style: pw.TextStyle(
              fontSize: size,
              fontWeight: isBold ? pw.FontWeight.bold : pw.FontWeight.normal,
              color: color,
            ),
          ),
          pw.Text(
            value,
            style: pw.TextStyle(
              fontSize: size,
              fontWeight: isBold ? pw.FontWeight.bold : pw.FontWeight.normal,
              color: color,
            ),
          ),
        ],
      ),
    );
  }

  static List<pw.Widget> _buildElegantCenter(
    pw.Context context,
    DocumentModel doc,
    BusinessProfile profile, {
    required List<PaymentDetail> payments,
    Uint8List? logoBytes,
    Uint8List? signatureBytes,
  }) {
    final title = doc.docType.displayName.toUpperCase();
    final primaryColor = PdfColor.fromHex('#0D47A1');
    final lightBlue = PdfColor.fromHex('#D6E4F0');

    final cName = doc.customerSnapshot?.name ?? 'Unknown Customer';
    final cEmail = doc.customerSnapshot?.email ?? '';
    final cPhone = doc.customerSnapshot?.phone ?? '';

    return [
      pw.Row(
        mainAxisAlignment: pw.MainAxisAlignment.center,
        crossAxisAlignment: pw.CrossAxisAlignment.center,
        children: [
          if (logoBytes != null) ...[
            pw.ClipOval(
              child: pw.Container(
                width: 32,
                height: 32,
                child: pw.Image(
                  pw.MemoryImage(logoBytes),
                  fit: pw.BoxFit.cover,
                ),
              ),
            ),
            pw.SizedBox(width: 16),
          ],
          pw.Text(
            profile.businessName,
            style: pw.TextStyle(fontSize: 32, color: primaryColor),
          ),
        ],
      ),
      pw.SizedBox(height: 16),
      pw.Row(
        mainAxisAlignment: pw.MainAxisAlignment.center,
        children: [
          if (profile.address != null && profile.address!.isNotEmpty)
            pw.Text(
              profile.address!,
              style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey600),
            ),
          if (profile.address != null &&
              profile.phone != null &&
              profile.address!.isNotEmpty &&
              profile.phone!.isNotEmpty)
            pw.Text(
              '   |   ',
              style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey600),
            ),
          if (profile.phone != null && profile.phone!.isNotEmpty)
            pw.Text(
              profile.phone!,
              style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey600),
            ),
          if (profile.phone != null &&
              profile.email != null &&
              profile.phone!.isNotEmpty &&
              profile.email!.isNotEmpty)
            pw.Text(
              '   |   ',
              style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey600),
            ),
          if (profile.email != null && profile.email!.isNotEmpty)
            pw.Text(
              profile.email!,
              style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey600),
            ),
        ],
      ),
      pw.SizedBox(height: 12),
      pw.Container(height: 2, color: lightBlue),
      pw.SizedBox(height: 32),
      pw.Row(
        mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Text(
                'Paid By',
                style: pw.TextStyle(
                  color: primaryColor,
                  fontWeight: pw.FontWeight.bold,
                  fontSize: 11,
                ),
              ),
              pw.SizedBox(height: 6),
              pw.Text(cName, style: const pw.TextStyle(fontSize: 11)),
              pw.SizedBox(height: 6),
              if (cEmail.isNotEmpty)
                pw.Text(cEmail, style: const pw.TextStyle(fontSize: 11)),
            ],
          ),
          pw.Text(
            title,
            style: pw.TextStyle(
              color: primaryColor,
              fontWeight: pw.FontWeight.bold,
              fontSize: 28,
            ),
          ),
        ],
      ),
      pw.SizedBox(height: 32),
      pw.Row(
        crossAxisAlignment: pw.CrossAxisAlignment.end,
        mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
        children: [
          pw.Expanded(
            child: pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                pw.Text(
                  'Booking Details',
                  style: pw.TextStyle(
                    color: primaryColor,
                    fontWeight: pw.FontWeight.bold,
                    fontSize: 11,
                  ),
                ),
                pw.SizedBox(height: 8),
                pw.Row(
                  children: [
                    pw.SizedBox(
                      width: 100,
                      child: pw.Text(
                        'Issue Date',
                        style: const pw.TextStyle(fontSize: 11),
                      ),
                    ),
                    pw.Text(
                      DateFormatter.format(doc.issueDate),
                      style: const pw.TextStyle(fontSize: 11),
                    ),
                  ],
                ),
                pw.SizedBox(height: 6),
                pw.Row(
                  children: [
                    pw.SizedBox(
                      width: 100,
                      child: pw.Text(
                        'Due Date',
                        style: const pw.TextStyle(fontSize: 11),
                      ),
                    ),
                    pw.Text(
                      DateFormatter.format(doc.dueDate),
                      style: const pw.TextStyle(fontSize: 11),
                    ),
                  ],
                ),
              ],
            ),
          ),
          pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.end,
            children: [
              pw.Row(
                children: [
                  pw.SizedBox(
                    width: 80,
                    child: pw.Text(
                      'Receipt #',
                      style: pw.TextStyle(
                        color: primaryColor,
                        fontWeight: pw.FontWeight.bold,
                        fontSize: 11,
                      ),
                    ),
                  ),
                  pw.Text(
                    doc.docNumber,
                    style: const pw.TextStyle(fontSize: 11),
                  ),
                ],
              ),
              pw.SizedBox(height: 6),
              pw.Row(
                children: [
                  pw.SizedBox(
                    width: 80,
                    child: pw.Text(
                      'Receipt Date',
                      style: pw.TextStyle(
                        color: primaryColor,
                        fontWeight: pw.FontWeight.bold,
                        fontSize: 11,
                      ),
                    ),
                  ),
                  pw.Text(
                    DateFormatter.format(doc.issueDate),
                    style: const pw.TextStyle(fontSize: 11),
                  ),
                ],
              ),
            ],
          ),
        ],
      ),
      pw.SizedBox(height: 24),
      pw.Container(
        decoration: pw.BoxDecoration(
          border: pw.Border.all(color: primaryColor),
        ),
        child: pw.Column(
          children: [
            pw.Container(
              color: primaryColor,
              padding: const pw.EdgeInsets.symmetric(
                vertical: 8,
                horizontal: 12,
              ),
              child: pw.Row(
                children: [
                  pw.Expanded(
                    flex: 1,
                    child: pw.Text(
                      'Quantity',
                      style: pw.TextStyle(
                        color: PdfColors.white,
                        fontWeight: pw.FontWeight.bold,
                        fontSize: 10,
                      ),
                    ),
                  ),
                  pw.Expanded(
                    flex: 3,
                    child: pw.Text(
                      'Description',
                      style: pw.TextStyle(
                        color: PdfColors.white,
                        fontWeight: pw.FontWeight.bold,
                        fontSize: 10,
                      ),
                    ),
                  ),
                  pw.Expanded(
                    flex: 2,
                    child: pw.Align(
                      alignment: pw.Alignment.centerRight,
                      child: pw.Text(
                        'Unit Price',
                        style: pw.TextStyle(
                          color: PdfColors.white,
                          fontWeight: pw.FontWeight.bold,
                          fontSize: 10,
                        ),
                      ),
                    ),
                  ),
                  pw.Expanded(
                    flex: 2,
                    child: pw.Align(
                      alignment: pw.Alignment.centerRight,
                      child: pw.Text(
                        'Amount',
                        style: pw.TextStyle(
                          color: PdfColors.white,
                          fontWeight: pw.FontWeight.bold,
                          fontSize: 10,
                        ),
                      ),
                    ),
                  ),
                ],
              ),
            ),
            ...doc.items.map((item) {
              return pw.Padding(
                padding: const pw.EdgeInsets.symmetric(
                  vertical: 12,
                  horizontal: 12,
                ),
                child: pw.Row(
                  children: [
                    pw.Expanded(
                      flex: 1,
                      child: pw.Align(
                        alignment: pw.Alignment.centerRight,
                        child: pw.Text(
                          item.quantity.toString(),
                          style: const pw.TextStyle(fontSize: 11),
                        ),
                      ),
                    ),
                    pw.SizedBox(width: 20),
                    pw.Expanded(
                      flex: 3,
                      child: pw.Text(
                        item.title,
                        style: const pw.TextStyle(fontSize: 11),
                      ),
                    ),
                    pw.Expanded(
                      flex: 2,
                      child: pw.Align(
                        alignment: pw.Alignment.centerRight,
                        child: pw.Text(
                          CurrencyFormatter.format(
                            item.unitPrice,
                            symbol: 'Rs.',
                          ),
                          style: const pw.TextStyle(fontSize: 11),
                        ),
                      ),
                    ),
                    pw.Expanded(
                      flex: 2,
                      child: pw.Align(
                        alignment: pw.Alignment.centerRight,
                        child: pw.Text(
                          CurrencyFormatter.format(
                            item.lineTotal,
                            symbol: 'Rs.',
                          ),
                          style: const pw.TextStyle(fontSize: 11),
                        ),
                      ),
                    ),
                  ],
                ),
              );
            }),
            pw.Container(height: 1, color: primaryColor),
            pw.Padding(
              padding: const pw.EdgeInsets.symmetric(
                vertical: 8,
                horizontal: 12,
              ),
              child: pw.Row(
                children: [
                  pw.Expanded(flex: 4, child: pw.SizedBox()),
                  pw.Expanded(
                    flex: 2,
                    child: pw.Text(
                      'Subtotal',
                      style: const pw.TextStyle(fontSize: 11),
                    ),
                  ),
                  pw.Expanded(
                    flex: 2,
                    child: pw.Align(
                      alignment: pw.Alignment.centerRight,
                      child: pw.Text(
                        CurrencyFormatter.format(doc.subtotal, symbol: 'Rs.'),
                        style: const pw.TextStyle(fontSize: 11),
                      ),
                    ),
                  ),
                ],
              ),
            ),
            if (doc.totalTaxAmount > 0)
              pw.Padding(
                padding: const pw.EdgeInsets.symmetric(
                  vertical: 8,
                  horizontal: 12,
                ),
                child: pw.Row(
                  children: [
                    pw.Expanded(flex: 4, child: pw.SizedBox()),
                    pw.Expanded(
                      flex: 2,
                      child: pw.Text(
                        'Tax',
                        style: const pw.TextStyle(fontSize: 11),
                      ),
                    ),
                    pw.Expanded(
                      flex: 2,
                      child: pw.Align(
                        alignment: pw.Alignment.centerRight,
                        child: pw.Text(
                          CurrencyFormatter.format(
                            doc.totalTaxAmount,
                            symbol: 'Rs.',
                          ),
                          style: const pw.TextStyle(fontSize: 11),
                        ),
                      ),
                    ),
                  ],
                ),
              ),
            if (doc.overallDiscountAmount > 0)
              pw.Padding(
                padding: const pw.EdgeInsets.symmetric(
                  vertical: 8,
                  horizontal: 12,
                ),
                child: pw.Row(
                  children: [
                    pw.Expanded(flex: 4, child: pw.SizedBox()),
                    pw.Expanded(
                      flex: 2,
                      child: pw.Text(
                        'Discount',
                        style: const pw.TextStyle(fontSize: 11),
                      ),
                    ),
                    pw.Expanded(
                      flex: 2,
                      child: pw.Align(
                        alignment: pw.Alignment.centerRight,
                        child: pw.Text(
                          '-${CurrencyFormatter.format(doc.overallDiscountAmount, symbol: 'Rs.')}',
                          style: const pw.TextStyle(fontSize: 11),
                        ),
                      ),
                    ),
                  ],
                ),
              ),
            pw.Container(height: 1, color: primaryColor),
            pw.Container(
              color: lightBlue,
              padding: const pw.EdgeInsets.symmetric(
                vertical: 12,
                horizontal: 12,
              ),
              child: pw.Row(
                children: [
                  pw.Expanded(flex: 4, child: pw.SizedBox()),
                  pw.Expanded(
                    flex: 2,
                    child: pw.Text(
                      'Total',
                      style: pw.TextStyle(
                        color: primaryColor,
                        fontWeight: pw.FontWeight.bold,
                        fontSize: 12,
                      ),
                    ),
                  ),
                  pw.Expanded(
                    flex: 2,
                    child: pw.Align(
                      alignment: pw.Alignment.centerRight,
                      child: pw.Text(
                        CurrencyFormatter.format(
                          doc.totalAmount,
                          symbol: 'Rs.',
                        ),
                        style: pw.TextStyle(
                          color: primaryColor,
                          fontWeight: pw.FontWeight.bold,
                          fontSize: 12,
                        ),
                      ),
                    ),
                  ),
                ],
              ),
            ),
          ],
        ),
      ),
      pw.Spacer(),
      pw.Row(
        crossAxisAlignment: pw.CrossAxisAlignment.end,
        mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
        children: [
          pw.Expanded(
            child: pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                if (doc.notes != null && doc.notes!.isNotEmpty) ...[
                  pw.Text(
                    'Notes',
                    style: pw.TextStyle(
                      color: primaryColor,
                      fontWeight: pw.FontWeight.bold,
                      fontSize: 11,
                    ),
                  ),
                  pw.SizedBox(height: 4),
                  pw.Text(doc.notes!, style: const pw.TextStyle(fontSize: 11)),
                  pw.SizedBox(height: 16),
                ],
                _buildPaymentDetails(
                  doc,
                  payments,
                  profile,
                  primaryColor: primaryColor,
                ),
              ],
            ),
          ),
          if (signatureBytes != null)
            pw.Column(
              children: [
                pw.Image(pw.MemoryImage(signatureBytes), height: 50),
                pw.Container(
                  width: 150,
                  child: pw.Divider(color: primaryColor),
                ),
                pw.Text(
                  'Authorized Signature',
                  style: pw.TextStyle(fontSize: 10, color: primaryColor),
                ),
              ],
            ),
        ],
      ),
    ];
  }
}
