import re

with open('lib/features/pdf_engine/document_pdf_generator.dart', 'r', encoding='utf-8') as f:
    content = f.read()

# Replace footer block
footer_pattern = r"footer: \(context\) => pw\.Container\(\s*margin: const pw\.EdgeInsets\.only\(top: 16\),\s*child: pw\.Row\([\s\S]*?pw\.Text\(\s*'Page \$\{context\.pageNumber\} of \$\{context\.pagesCount\}',\s*style: const pw\.TextStyle\(fontSize: 8, color: PdfColors\.grey\),\s*\),\s*\],\s*\),\s*\),"
new_footer = """footer: (context) => pw.Container(
          margin: const pw.EdgeInsets.only(top: 25, left: 5),
          child: pw.Row(
            mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
            children: [
              pw.UrlLink(
                destination:
                    'https://play.google.com/store/apps/details?id=com.example.real_invoice',
                child: pw.Text(
                  'Generated by Invoz App',
                  style: pw.TextStyle(
                    fontSize: 9,
                    color: PdfColor.fromHex('#2563EB'),
                  ),
                ),
              ),
              pw.Text(
                'Page  of ',
                style: const pw.TextStyle(fontSize: 8, color: PdfColors.grey),
              ),
            ],
          ),
        ),"""

content = re.sub(footer_pattern, new_footer, content)

# Replace _buildPaymentDetails
payment_pattern = r"static pw\.Widget _buildPaymentDetails\([\s\S]*?}\s*}\s*}\s*}\s*}\s*return pw\.Container\(\s*child: pw\.Row\([\s\S]*?\]\s*,\s*\)\s*,\s*\)\s*;"
new_payment = """static pw.Widget _buildPaymentDetails(
    DocumentModel doc,
    List<PaymentDetail> payments,
    BusinessProfile profile, {
    PdfColor? primaryColor,
  }) {
    PaymentDetail? bankDetail;
    if (doc.selectedBankDetailId != null &&
        doc.selectedBankDetailId != 'none') {
      try {
        bankDetail = payments.firstWhere(
          (p) => p.id == doc.selectedBankDetailId,
        );
      } catch (_) {}
    }

    if (bankDetail == null && doc.selectedBankDetailId != 'none') {
      final banks = payments.where((p) => p.type == 'Bank').toList();
      if (banks.isNotEmpty) bankDetail = banks.first;
    }

    PaymentDetail? upiDetail;
    if (doc.selectedUpiDetailId != null && doc.selectedUpiDetailId != 'none') {
      try {
        upiDetail = payments.firstWhere((p) => p.id == doc.selectedUpiDetailId);
      } catch (_) {}
    }

    if (upiDetail == null && doc.selectedUpiDetailId != 'none') {
      final upis = payments.where((p) => p.type == 'UPI').toList();
      if (upis.isNotEmpty) upiDetail = upis.first;
    }

    final hasBank = bankDetail != null;
    final hasUpi = upiDetail != null;

    if (!doc.includePaymentDetails || doc.docType == DocumentType.receipt) {
      return pw.SizedBox();
    }
    if (!hasBank && !hasUpi) return pw.SizedBox();

    return pw.Container(
      child: pw.Row(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Column(
            children: [
              pw.Container(
                width: 60,
                height: 60,
                padding: const pw.EdgeInsets.all(4),
                decoration: pw.BoxDecoration(
                  color: PdfColors.white,
                  borderRadius: const pw.BorderRadius.all(
                    pw.Radius.circular(6),
                  ),
                  border: pw.Border.all(color: PdfColors.grey400, width: 1),
                ),
                child: hasUpi
                    ? pw.BarcodeWidget(
                        barcode: pw.Barcode.qrCode(),
                        data:
                            'upi://pay?pa=&pn=&am=',
                      )
                    : pw.BarcodeWidget(
                        barcode: pw.Barcode.qrCode(),
                        data: 'https://invoice-c1603.web.app',
                      ),
              ),
              pw.SizedBox(height: 4),
              pw.Text(
                'Scan to Pay',
                style: pw.TextStyle(
                  fontSize: 8,
                  fontWeight: pw.FontWeight.bold,
                  color: PdfColors.grey700,
                ),
              ),
            ],
          ),
          pw.SizedBox(width: 6),
          pw.Expanded(
            child: pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                pw.Text(
                  'PAYMENT DETAILS',
                  style: pw.TextStyle(
                    fontSize: 9,
                    fontWeight: pw.FontWeight.bold,
                    letterSpacing: 0.6,
                    color: primaryColor ?? PdfColors.grey800,
                  ),
                ),
                pw.SizedBox(height: 4),
                if (hasUpi)
                  pw.Text(
                    'UPI: ',
                    style: pw.TextStyle(
                      fontSize: 8,
                      fontWeight: pw.FontWeight.bold,
                      color: PdfColors.grey700,
                    ),
                  ),

                if (hasBank) ...[
                  pw.Text(
                    'Bank: ',
                    style: pw.TextStyle(
                      fontSize: 8,
                      fontWeight: pw.FontWeight.bold,
                      color: PdfColors.grey700,
                    ),
                  ),

                  pw.Text(
                    'A/C: ',
                    style: pw.TextStyle(
                      fontSize: 8,
                      fontWeight: pw.FontWeight.bold,
                      color: PdfColors.grey700,
                    ),
                  ),
                  if (bankDetail.extra != null &&
                      bankDetail.extra!.trim().isNotEmpty)
                    pw.Text(
                      'IFSC: ',
                      style: pw.TextStyle(
                        fontSize: 8,
                        fontWeight: pw.FontWeight.bold,
                        color: PdfColors.grey700,
                      ),
                    ),
                ],
              ],
            ),
          ),
        ],
      ),
    );"""

content = re.sub(payment_pattern, new_payment, content)

with open('lib/features/pdf_engine/document_pdf_generator.dart', 'w', encoding='utf-8') as f:
    f.write(content)
