import re

with open('lib/features/pdf_engine/document_pdf_generator.dart', 'r', encoding='utf-8') as f:
    content = f.read()

# 1. Update the Footer "Generated by Invoz App"
footer_pattern = r"pw\.Text\(\s*'Generated by Invoz App',\s*style: const pw\.TextStyle\(fontSize: 8, color: PdfColors\.grey\),\s*\)"
footer_replacement = r"""pw.UrlLink(
                  destination: 'https://play.google.com/store/apps/details?id=com.example.real_invoice',
                  child: pw.Text(
                    'Generated by Invoz App',
                    style: pw.TextStyle(
                      fontSize: 9,
                      color: PdfColor.fromHex('#2563EB'), # Make it more visible (Blue)
                      decoration: pw.TextDecoration.underline,
                    ),
                  ),
                )"""
content = re.sub(footer_pattern, footer_replacement, content)

# 2. Update the Stamp UI formatting to match Signature
# Classic Stamp
classic_stamp = r"pw\.Image\(pw\.MemoryImage\(stampBytes\), height: 50\)"
classic_stamp_replace = r"""pw.Column(
                      children: [
                        pw.Image(pw.MemoryImage(stampBytes), height: 40),
                        pw.SizedBox(height: 4),
                        pw.Container(width: 120, height: 1.5, color: borderColor),
                        pw.SizedBox(height: 4),
                        pw.Text(
                          'Stamp',
                          style: pw.TextStyle(
                            fontSize: 9,
                            fontWeight: pw.FontWeight.bold,
                            color: primaryColor,
                          ),
                        ),
                      ],
                    )"""

# Wait, the previous replace placed: child: pw.Image(pw.MemoryImage(stampBytes), height: 50), for ALL of them.
# Let's write a targeted regex for the stamp block.
stamp_pattern = r"if \(stampBytes != null && doc\.showStamp\)\s*pw\.Padding\(\s*padding: const pw\.EdgeInsets\.only\(right: 20\),\s*child: pw\.Image\(pw\.MemoryImage\(stampBytes\), height: 50\),\s*\),"
stamp_replacement = r"""if (stampBytes != null && doc.showStamp)
                  pw.Padding(
                    padding: const pw.EdgeInsets.only(right: 20),
                    child: pw.Column(
                      children: [
                        pw.Image(pw.MemoryImage(stampBytes), height: 50),
                        pw.SizedBox(height: 4),
                        pw.Container(
                          width: 150,
                          child: pw.Divider(color: primaryColor),
                        ),
                        pw.SizedBox(height: 4),
                        pw.Text(
                          'Stamp',
                          style: pw.TextStyle(
                            fontSize: 10,
                            color: primaryColor,
                          ),
                        ),
                      ],
                    ),
                  ),"""

content = re.sub(stamp_pattern, stamp_replacement, content)

with open('lib/features/pdf_engine/document_pdf_generator.dart', 'w', encoding='utf-8') as f:
    f.write(content)
