// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCeg_4FJPVqtsObClEWarAwLGYnMJq1EU',
    appId: '1:714420260814:web:53c3ebce7af0e81228659f',
    messagingSenderId: '714420260814',
    projectId: 'invoice-c1603',
    authDomain: 'invoice-c1603.firebaseapp.com',
    storageBucket: 'invoice-c1603.firebasestorage.app',
    measurementId: 'G-PQ16WNTY78',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlYaDSFZvO4GnT6Xf0R-vgCzvb9PMQquo',
    appId: '1:714420260814:android:513bdae45ce857ec28659f',
    messagingSenderId: '714420260814',
    projectId: 'invoice-c1603',
    storageBucket: 'invoice-c1603.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAN6kGU7D7dTHRW4N-68hd2md3ynScy0k',
    appId: '1:714420260814:ios:91265190be23854b28659f',
    messagingSenderId: '714420260814',
    projectId: 'invoice-c1603',
    storageBucket: 'invoice-c1603.firebasestorage.app',
    iosBundleId: 'com.example.realInvoice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAN6kGU7D7dTHRW4N-68hd2md3ynScy0k',
    appId: '1:714420260814:ios:91265190be23854b28659f',
    messagingSenderId: '714420260814',
    projectId: 'invoice-c1603',
    storageBucket: 'invoice-c1603.firebasestorage.app',
    iosBundleId: 'com.example.realInvoice',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCeg_4FJPVqtsObClEWarAwLGYnMJq1EU',
    appId: '1:714420260814:web:6060900269828b2c28659f',
    messagingSenderId: '714420260814',
    projectId: 'invoice-c1603',
    authDomain: 'invoice-c1603.firebaseapp.com',
    storageBucket: 'invoice-c1603.firebasestorage.app',
    measurementId: 'G-CBPRNC422H',
  );
}
