// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCe0qVeaCgIjUS0fcAvSSbfqNRSGv50e7Q',
    appId: '1:556388897712:web:3c7eaf754795d4abc57c75',
    messagingSenderId: '556388897712',
    projectId: 'invoz-d9222',
    authDomain: 'invoz-d9222.firebaseapp.com',
    storageBucket: 'invoz-d9222.firebasestorage.app',
    measurementId: 'G-V7M1GL1KZ0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHbafvv0jXy0850t0w32ak1Urx6oC9xho',
    appId: '1:556388897712:android:66f9e84300096a4ec57c75',
    messagingSenderId: '556388897712',
    projectId: 'invoz-d9222',
    storageBucket: 'invoz-d9222.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAwGlljhuJX7SyGIEYYjk2mNY5g0UKFZ4',
    appId: '1:556388897712:ios:a116cf5131bb2d88c57c75',
    messagingSenderId: '556388897712',
    projectId: 'invoz-d9222',
    storageBucket: 'invoz-d9222.firebasestorage.app',
    iosClientId: '556388897712-sdlhefbjlps4ag4c7rifms6njf9u1e5r.apps.googleusercontent.com',
    iosBundleId: 'com.invoice.invoz',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAwGlljhuJX7SyGIEYYjk2mNY5g0UKFZ4',
    appId: '1:556388897712:ios:560d2a230ae55de2c57c75',
    messagingSenderId: '556388897712',
    projectId: 'invoz-d9222',
    storageBucket: 'invoz-d9222.firebasestorage.app',
    iosClientId: '556388897712-3c0ku6i520av8is1qjha804ekjk9udvd.apps.googleusercontent.com',
    iosBundleId: 'com.example.realInvoice',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCe0qVeaCgIjUS0fcAvSSbfqNRSGv50e7Q',
    appId: '1:556388897712:web:568904fad8d98065c57c75',
    messagingSenderId: '556388897712',
    projectId: 'invoz-d9222',
    authDomain: 'invoz-d9222.firebaseapp.com',
    storageBucket: 'invoz-d9222.firebasestorage.app',
    measurementId: 'G-V8P9W3636S',
  );
}
